### PR TITLE
`saw-core-coq`: fixes for latest Rocq (v9.1)

### PR DESCRIPTION
**Pull request by chathhorn-galois**
This PR updates `saw-core-coq` to work with the latest released version of Rocq (9.1). It does not maintain backward compatibility with versions < 9. Changes:
- Remove duplicate `Import SAWCorePrelude` and `Import CryptolPrimitivesForSAWCore` statements in generated files. Not strictly necessary for the upgrade.
- Remove dependency on [Coq.Numbers.Cyclic.ZModulo.ZModulo](https://rocq-prover.org/doc/V8.16.1/stdlib/Coq.Numbers.Cyclic.ZModulo.ZModulo.html) from `SAWCoreScaffolding.v`. It was deprecated in Coq 8.17 and later removed from the standard library (see discussion below). Comment from the 8.17 changelog:
  > *Deprecated:* Cyclic.ZModulo.ZModulo because there have been no known use cases for this module and because it does not implement Z/nZ for arbitrary n as one might expect based on the name. The same construction will remain a part of the Coq test suite to ensure consistency of CyclicAxioms.
- Replace `Hint` terms with global references (to those terms) in `SAWCoreScaffolding.v` to avoid the `Declaring arbitrary terms as hints is forbidden` error introduced in [v8.20 (or maybe 9.1)](https://github.com/rocq-prover/rocq/pull/20373).
- Replace `From Coq` with `From Stdlib` in import statements. The `From Coq` bit is currently only deprecated, so not strictly necessary, but the change drastically cuts down on the number of warnings Coq will generate. Also replace `Coq` with `Stdlib` (or nothing) where necessary in qualified names.
- Add explicit `#[global]` locality modifier to `Instance` definitions in `Cryptol.sawcore` and `Prelude.sawcore`. `Instance` definitions with no modifier were changed to have a default locality of `export` in [v8.18](https://rocq-prover.org/doc/v8.18/refman/changes.html).
- Update dependency on [coq-bits](https://github.com/rocq-community/bits) to the current `HEAD` of the `master` branch in the linked repo in `ci.yml` and documentation. The version currently-released in opam is several years out of date.

`rocq` is still producing many warnings after these changes that should be addressed in a future PR, but this should get things working with v9.1. Also: I mostly avoided Coq => Rocq renaming because it's all over the place -- that might be worth doing in a separate big PR as well.

### CODE REVIEW

File: saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v [hunk 1]
```diff
@@ -361,19 +360,34 @@ Global Hint Resolve (0%Z : Integer) : inh.
...
+Definition toIntMod (n : nat) : Integer -> IntMod n :=
+  fun i => Z.modulo i (Z.of_nat n).
+
+(* Convert from IntMod n to Integer. This is the identity since IntMod n is just Z. *)
+Definition fromIntMod (n : nat) : (IntMod n) -> Integer :=
+  fun i => i.
+
+(* Equality on IntMod - just use Z equality since values are already reduced. *)
+Definition intModEq (n : nat) (a : IntMod n) (b : IntMod n) : bool :=
+  Z.eqb a b.
```
Comment (sauclovian-g) [inline saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: I know you didn't write this... but at some point it should get changed to `eqb` and not `eq`.

File: .github/workflows/ci.yml [hunk 2]
```diff
@@ -514,9 +514,21 @@ jobs:
...
+      # opam-released version when available.
+      - working-directory: saw-core-coq/coq
+        run: |
+          opam install -y coq=9.1.0 # coq-* packages include compatibility shims (e.g., coq_makefile).
+          git clone https://github.com/rocq-community/bits.git
+          cd bits
+          git config set advice.detachedHead false
+          git checkout f50fc3e5f1eabcb0b0b94c8d25f75e61a255c2ba
+          opam exec -- make -j
+          opam exec -- make install
```
Comment (RyanGlScott) [inline .github/workflows/ci.yml]: FWIW, you can greatly simplify the logic here by using [`opam pin`](https://opam.ocaml.org/doc/Manual.html#Pinning) instead. Something like:


```suggestion
          opam pin -y coq-bits https://github.com/rocq-community/bits.git#f50fc3e5f1eabcb0b0b94c8d25f75e61a255c2ba
```

Comment (chathhorn-galois) [reply .github/workflows/ci.yml]: Oh nice, thanks!

File: saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v [hunk 3]
```diff
@@ -362,18 +366,17 @@ Global Hint Resolve (0%Z : Integer) : inh.
 (* NOTE: the following will be nonsense for values of n <= 1 *)
 Definition IntMod (n : nat) := Z.
 Definition toIntMod (n : nat) : Integer -> IntMod n := fun i => Z.modulo i (Z.of_nat n).
-Definition fromIntMod (n : nat) : (IntMod n) -> Integer := ZModulo.to_Z (Pos.of_nat n).
-Local Notation "[| a |]_ n" := (to_Z (Pos.of_nat n) a) (at level 0, a at level 99).
+Definition fromIntMod (n : nat) : (IntMod n) -> Integer := fun i => i.
```
Comment (RyanGlScott) [inline saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: Am I reading this correctly that the definition of `fromIntMod` changed from `ZModulo.to_Z (Pos.of_nat n)` (which reduces the argument modulo `n`) to just the identity function? Why is this change correct?

File: saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v [hunk 4]
```diff
@@ -362,18 +366,17 @@ Global Hint Resolve (0%Z : Integer) : inh.
...
 Definition intModEq (n : nat) (a : IntMod n) (b : IntMod n) : bool
-  := Z.eqb [| a |]_n [| b |]_n.
+  := Z.eqb a b.
```
Comment (RyanGlScott) [inline saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: Similarly, doesn't removing the uses of `[| ... |]_n` here change the semantics of this function?

File: saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v (hunk 3 above)
Comment (chathhorn-galois) [reply saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: Thanks -- it looks like `fromIntMod` should just be defined the same as `toIntMod` and `intModEq` should similarly reduce its args `mod n` before `eqb`. The rest of the changes here are just inlined definitions from `ZModulo`.

But I'm kinda confused about the original intention of this. Unless I'm misunderstanding, it looks like `ZModulo` is about arithmetic modulo  `2^n`, not modulo `n`, so the original definition of `intModEq a b` appears to be `Z.eqb (a mod 2^n) (b mod 2^n)`, which doesn't seem to track with the original definition of `toIntMod` (or what I think is the intention in `Cryptol.sawcore`)?

Comment (RyanGlScott) [reply saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: > it looks like `fromIntMod` should just be defined the same as `toIntMod` and `intModEq` should similarly reduce its args `mod n` before `eqb`.

Oh, perhaps my understanding of what this code is doing is flawed. Where exactly does this reduction step happen? The new definition of `fromIntMod` is just `fun i => i`, which (at a first glance) appears to be a no-op. Is there an implicit reduction step happening somewhere?

> But I'm kinda confused about the original intention of this. Unless I'm misunderstanding, it looks like `ZModulo` is about arithmetic modulo `2^n`, not modulo `n`, so the original definition of `intModEq a b` appears to be `Z.eqb (a mod 2^n) (b mod 2^n)`, which doesn't seem to track with the original definition of `toIntMod` (or what I think is the intention in `Cryptol.sawcore`)?

Oh, that is a bit unfortunate if true. Is this a change introduced in Rocq 9.0.0? Back in the 8.* days of Coq at least, `Z.modulo` was modulo `n` (for any `n`), not just things that are equal to `2^n`.

Comment (chathhorn-galois) [reply saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: Oh by `ZModulo` I specifically mean this [Coq.Numbers.Cyclic.ZModulo.ZModulo](https://rocq-prover.org/doc/V8.16.1/stdlib/Coq.Numbers.Cyclic.ZModulo.ZModulo.html) that was removed from the standard library around v8.17 or so.

Comment (chathhorn-galois) [reply saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: Wait -- it seems like my changes here should be alright because we're reducing `mod n` after every operation.

AFAICT the options are: (1) reduce `mod n` for `toIntMod` and then after every operation, making `fromIntMod` just `id` or (2) reduce `mod n` in `fromIntMod` and don't reduce after any operation on `IntMod`s (similarly making `toIntMod := id`, which probably makes more sense and what I was imagining I'd done for some reason).

My (further) confusion is just that the original definition looks like it was buggy, but I'm not very confident about that.

Comment (RyanGlScott) [reply saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: I apologize, I think I misunderstood what was going on here. Specifically, `IntMod n` isn't a separate type from `Integer`, but rather they're both type synonyms around `Z`. Now that I've taken the time to more closely read the surrounding code, I now see why the definition of `fromIntMod` is the way it is, and I think it's reasonable. (Sorry for the confusion!)

> My (further) confusion is just that the original definition looks like it was buggy, but I'm not very confident about that.

I _think_ that in Coq 8.*, `ZModulo` referred to [this](https://rocq-prover.org/doc/V8.16.1/stdlib/Coq.Numbers.Cyclic.ZModulo.ZModulo.html), which appears to be modulo `n` for any natural number `n`. If this has been removed in Rocq 9.0, do you know if there is a new home for this somewhere?

Comment (chathhorn-galois) [reply saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: > I _think_ that in Coq 8.*, `ZModulo` referred to [this](https://rocq-prover.org/doc/V8.16.1/stdlib/Coq.Numbers.Cyclic.ZModulo.ZModulo.html), which appears to be modulo `n` for any natural number `n`. If this has been removed in Rocq 9.0, do you know if there is a new home for this somewhere?

Yeah, that's the one. Notice the `digits` variable becomes the explicit parameter, but `to_Z x := x mod wB` where `wB := 2 ^ digits`:
```
 Variable digits : positive.
 Definition wB := base digits.

 Definition t := Z.
 Definition zdigits := Zpos digits.
 Definition to_Z x := x mod wB.
```

The comment in the 8.17 [changelog](https://rocq-prover.org/doc/V8.17.0/refman/changes.html) (I guess it was only deprecated at that point):
```
Deprecated: Cyclic.ZModulo.ZModulo because there have been no known use cases for this module and
because it does not implement Z/nZ for arbitrary n as one might expect based on the name. The same
construction will remain a part of the Coq test suite to ensure consistency of CyclicAxioms.
```

Comment (RyanGlScott) [reply saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: Wow, good find. If that's the case, then that does cast a large shadow of doubt on both the old and new implementations of `IntMod` in `saw-core-coq`. (That is to say, the new code isn't any less broken than the old code.)

Zooming out a bit, I feel like this discussion is perhaps detracting a bit from the overall theme of upgrading to Rocq 9.0.0 (sorry about that, I got carried away). I think we should open a separate issue about figuring out how to model `IntMod` properly.

Comment (chathhorn-galois) [reply saw-core-coq/coq/handwritten/CryptolToCoq/SAWCoreScaffolding.v]: I reworked these definitions to be closer to the original so the changes are more clear. Now:
- `toIntMod n i :=` unchanged -- I think this should just be `id`, but I left it as `Z.modulo i n` 
- `fromIntMod n i :=` original definition effectively: `Z.modulo i (2^n)`, new definition: `Z.modulo i n`
- `intModEq n a b :=` original definition effectively: `Z.eqb (Z.modulo a (2^n)) (Z.modulo b (2^n))`, new definition: `Z.eqb (Z.modulo a n) (Z.modulo b n)`
- `IntModAdd`/`IntModSub`/`IntModMul`/`IntModNeg`: these are all effectively unchanged (just inlined definitions).

File: .github/workflows/ci.yml [hunk 5]
```diff
@@ -514,9 +514,16 @@ jobs:
         with:
           ocaml-compiler: "4.14"
 
-      - run: opam repo add coq-released https://coq.inria.fr/opam/released
+      - run: opam repo add rocq-released https://rocq-prover.org/opam/released
 
-      - run: opam install -y coq=8.15.2 coq-bits=1.1.0
+      - run: opam pin add -y rocq-prover 9.0.0
```
Comment (sauclovian-g) [inline .github/workflows/ci.yml:519]: 9.0 or 9.1?

Comment (RyanGlScott) [reply .github/workflows/ci.yml:519]: On a similar note, it appears that we install both `rocq-prover-9.0.0` and `coq-9.1.0`. What is the difference between these two packages? Do we need both?

Comment (chathhorn-galois) [reply .github/workflows/ci.yml:519]: `rocq-prover` is a metapackage that depends on `rocq-stdlib` and `rocq-core` (which itself depends on `rocq-runtime`). Currently the latest `rocq-core` (including the `rocq` executable) is at version `9.1.0` while `rocq-stdlib` is at version `9.0.0`. It does look like it might be worth pinning the versions of `rocq-stdlib` and `rocq-core` because `rocq-prover` doesn't seem to put any version constraints on them as far as I can tell.

The `coq-9.1.0` package includes compatibility shims (like the `coqc` and `coq_makefile` executables) just needed for building the `coq-bits` package.

Comment (RyanGlScott) [reply .github/workflows/ci.yml:519]: Interesting! I didn't realize that `coq-bits` was the thing that specifically required legacy shims. I guess that makes sense, considering that it's not named `rocq-bits` yet :)

It's rather interesting that there is a Rocq 9.1.0 release, but `rocq-stdlib` is still on 9.0.0. Are the two versioned separately?

Comment (chathhorn-galois) [reply .github/workflows/ci.yml:519]: Yeah, `rocq-stdlib` and `rocq-core` seem to be versioned separately. I just made the versions of both explicit in the CI and the README.

Comment (sauclovian-g) [reply .github/workflows/ci.yml:519]: Weird. Did they change the source packaging for 9? It used to be one big source tarball.

Comment (chathhorn-galois) [reply .github/workflows/ci.yml:519]: It looks like they split up the packages into a "`coq`" metapackage depending on `coq-core` and `coq-stdlib` around [Coq 8.17](https://opam.ocaml.org/packages/coq/coq.8.17.0/) (compare: [Coq 8.16](https://opam.ocaml.org/packages/coq/coq.8.16.0/)).

Comment (sauclovian-g) [reply .github/workflows/ci.yml:519]: That's true for the opam packages, but the source download was unitary in 8.20.

ah I see, yes, as of 9.0 there's a separate download for the standard library: https://github.com/rocq-prover/stdlib/releases
