### ISSUE TITLE
SAW compilation failure with GHC 9.2.7

### ISSUE THREAD

**Issue by ramsdell** [GaloisInc/saw-script#1854]
On the master branch, SAW fails to compile using GHC 9.2.7.  The only error I can find is:
```
/Users/ramsdell/rep/saw-script/dist-newstyle/build/x86_64-osx/ghc-9.2.7/saw-core-0.1/build/Verifier/SAW/Lexer.hs:503:19: error: [-Werror]
    accepting non-standard pattern guards (use PatternGuards to suppress this message)
        (tagToEnum# (offset >=# 0#)),
        check <- alexIndexInt16OffAddr alex_check offset,
        (tagToEnum# (check ==# ord_c))
    |
503 |                   | GTE(offset,ILIT(0))
    |                   ^^^^^^^^^^^^^^^^^^^^^...
```

[all.txt](https://github.com/GaloisInc/saw-script/files/11222959/all.txt)

**Comment by RyanGlScott** [comment]
I can reproduce this. I'm guessing that you are using `alex-3.2.7.2`, which imposes a `PatternGuards` requirement that wasn't present in previous versions of `alex`. (See https://github.com/haskell/alex/pull/223#issuecomment-1507062850.) Thankfully, this shouldn't be difficult to fix. I'll prepare a patch.

**Comment by RyanGlScott** [comment]
See #1855 with a fix. That patch is a one-line change, so you can apply it locally if you want to get unstuck in the meantime.
