### PR TITLE
MIR: use layout info for tuple aggregates

### PR DESCRIPTION
**Pull request by spernsteiner**
Incorporates https://github.com/GaloisInc/mir-json/pull/218 and https://github.com/GaloisInc/crucible/pull/1743.  This also required a small tweak to the code for building `TupleShape`s (but not to anything else, since all the other tuple code uses the offsets from the `TupleShape` instead of computing them directly).

We actually had no test coverage for this change, since every crux-mir-comp test case that uses tuples happened to use `(u8, u8)`, where the real offsets are the same as the previous "hardcoded size=1" offsets.  I've changed a few of these to use `(u16, u16)` instead, and confirmed that they do fail without the `TupleShape` update.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Note that you'll likely need to regenerate the MIR-related test cases' expected outputs in order to make them use schema version 10. Also, make sure to update the README and the CHANGELOG to explicitly state that schema version 10 is being used.

**Comment by spernsteiner** [comment]
The CI build is failing with GHC 9.4.8 due to an unrelated change that was picked up during the submodule bump:
```
src/Mir/Intrinsics/Aggregate.hs:172:3: error:
Error:     • The type family application ‘(TypeError ...)’
        is no smaller than the instance head ‘MirAggregateFam sym ctx’
      (Use UndecidableInstances to permit this)
    • In the equations for closed type family ‘MirAggregateFam’
      In the type family declaration for ‘MirAggregateFam’
    |
172 |   MirAggregateFam sym ctx = TypeError
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```
The error message suggests enabling `UndecidableInstances` in `Mir/Intrinsics/Aggregate.hs`—is this a reasonable thing to do?

I guess this wasn't caught in Crucible CI because that one builds with GHC 9.6-9.10, but not with 9.4.

**Comment by RyanGlScott** [comment]
Good catch! I think it would be nice to continue supporting GHC 9.4 for now. I've opened https://github.com/GaloisInc/crucible/pull/1787 on the `crucible` side to fix this.

**Comment by spernsteiner** [comment]
CI is now passing on all three branches, so I'm going to start merging https://github.com/GaloisInc/mir-json/pull/218, https://github.com/GaloisInc/crucible/pull/1743, and finally this PR.
