### PR TITLE
Fix the `css` build post-#3215

### LINKED ISSUE #3243: `css` build broken after #3215
After https://github.com/GaloisInc/saw-script/pull/3215, `css` fails to build:

```
[1 of 2] Compiling Main             ( saw-tools/css/Main.hs, interpreted ) [Source file changed]

saw-tools/css/Main.hs:103:16: error: [GHC-83865]
    • Couldn't match expected type: IO C.CryptolEnv
                  with actual type: Maybe Cryptol.Parser.AST.ImportSpec
                                    -> IO C.CryptolEnv
    • Probable cause: ‘C.importCryptolModule’ is applied to too few arguments
      In a stmt of a 'do' block:
        cryenv' <- C.importCryptolModule
                     sc cryenv (Left inputModule) Nothing C.PublicAndPrivate Nothing
      In the expression:
        do let out = ...
           sc <- mkSharedContext
           C.scLoadPreludeModule sc
           C.scLoadCryptolModule sc
           ....
      In an equation for ‘cssMain’:
          cssMain css [inputModule, name]
            | cssMode css == NormalMode
            = do let out = ...
                 sc <- mkSharedContext
                 C.scLoadPreludeModule sc
                 ....
    |
103 |     cryenv' <- C.importCryptolModule sc cryenv (Left inputModule)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

saw-tools/css/Main.hs:104:29: error: [GHC-83865]
    • Couldn't match expected type ‘Bool’
                  with actual type ‘C.ImportVisibility’
    • In the fifth argument of ‘C.importCryptolModule’, namely
        ‘C.PublicAndPrivate’
      In a stmt of a 'do' block:
        cryenv' <- C.importCryptolModule
                     sc cryenv (Left inputModule) Nothing C.PublicAndPrivate Nothing
      In the expression:
        do let out = ...
           sc <- mkSharedContext
           C.scLoadPreludeModule sc
           C.scLoadCryptolModule sc
           ....
    |
104 |                     Nothing C.PublicAndPrivate Nothing
    |                             ^^^^^^^^^^^^^^^^^^

saw-tools/css/Main.hs:104:48: error: [GHC-83865]
    • Couldn't match expected type ‘C.ImportVisibility’
                  with actual type ‘Maybe a0’
    • In the sixth argument of ‘C.importCryptolModule’, namely
        ‘Nothing’
      In a stmt of a 'do' block:
        cryenv' <- C.importCryptolModule
                     sc cryenv (Left inputModule) Nothing C.PublicAndPrivate Nothing
      In the expression:
        do let out = ...
           sc <- mkSharedContext
           C.scLoadPreludeModule sc
           C.scLoadCryptolModule sc
           ....
    |
104 |                     Nothing C.PublicAndPrivate Nothing
    |                                                ^^^^^^^
```

### PR DESCRIPTION
**Pull request by RyanGlScott**
Also add `css` to `build.sh` to ensure that future changes do not cause the `css` build to regress.

Fixes https://github.com/GaloisInc/saw-script/issues/3243.

### CODE REVIEW

**Review by sauclovian-g — APPROVED** [review]

**Comment by RyanGlScott** [comment]
The CI is failing for unrelated reasons (https://github.com/GaloisInc/saw-script/issues/3245).
