### ISSUE TITLE
`crux-mir-comp` fails to compile after 1a8f0e0

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/saw-script#1460]
After 1a8f0e0, `crux-mir-comp` fails to compile:

```
[3 of 7] Compiling Mir.Compositional.Clobber ( src/Mir/Compositional/Clobber.hs, interpreted )

src/Mir/Compositional/Clobber.hs:27:20: error:
    Module ‘Crux.Types’ does not export ‘HasModel(..)’
   |
27 | import Crux.Types (HasModel(..))
   |                    ^^^^^^^^^^^^
```

This is related to GaloisInc/crucible#769.

**Comment by robdockins** [comment]
We should at least build crux-mir-comp as part of the CI.

**Comment by RyanGlScott** [comment]
Fixed in #1501.
