### PR TITLE
Fix the build with `alex-3.2.7.2`

### LINKED ISSUE #1854: SAW compilation failure with GHC 9.2.7
On the master branch, SAW fails to compile using GHC 9.2.7.  The only error I can find is:
```
/Users/ramsdell/rep/saw-script/dist-newstyle/build/x86_64-osx/ghc-9.2.7/saw-core-0.1/build/Verifier/SAW/Lexer.hs:503:19: error: [-Werror]
    accepting non-standard pattern guards (use PatternGuards to suppress this message)
        (tagToEnum# (offset >=# 0#)),
        check <- alexIndexInt16OffAddr alex_check offset,
        (tagToEnum# (check ==# ord_c))
    |
503 |                   | GTE(offset,ILIT(0))
    |                   ^^^^^^^^^^^^^^^^^^^^^...
```

[all.txt](https://github.com/GaloisInc/saw-script/files/11222959/all.txt)

### PR DESCRIPTION
**Pull request by RyanGlScott**
`alex-3.2.7.2` generates code that uses `PatternGuards`, but because `saw-core` does not specify a `default-language` in its `.cabal` file, it defaults to `Haskell98`, which does not include `PatternGuards`. Arguably, we should make `saw-core`'s `default-language` be `Haskell2010` (which _does_ include `PatternGuards`), but that would be a somewhat larger change. For the sake of restoring the build, this applies the simplest possible fix of enabling `PatternGuards` in the affected file.

Fixes #1854.

### CODE REVIEW

**Review by chameco — APPROVED** [review]
LGTM
